trading_indicators = {
    "Trend Indicators": {
        "Moving Averages (SMA & EMA)": "Simple Moving Average (SMA) is the average price over a specified period, providing a smoothed line that 'mirrors' historical price movements. Exponential Moving Average (EMA) gives more weight to recent prices, making it quicker to respond to new price changes. Traders use moving averages to identify trend direction and crossover signals (e.g., 50-day vs 200-day MA crossovers).",
        "Average Directional Index (ADX)": "A trend-strength indicator that measures the strength of a trend regardless of its direction. ADX is usually plotted with +DI and –DI lines (directional movement indicators); a high ADX value (e.g., above 25) indicates a strong trend, while a low value (e.g., below 20) suggests a weak or ranging market.",
        "Ichimoku Cloud": "A comprehensive indicator (Ichimoku Kinko Hyo) consisting of multiple lines (Tenkan-sen, Kijun-sen, Senkou Span A/B, Chikou) that together show support and resistance levels, as well as momentum and trend direction. The 'cloud' (area between Senkou Span A and B) projects future support/resistance. Ichimoku allows traders to gauge trend bias at a glance (price above cloud = bullish, below = bearish) along with potential entry signals from line crossovers.",
        "Parabolic SAR": "The Parabolic Stop and Reverse indicator places a series of dots (or 'parabolic' points) above or below the price to signal trend direction. In an uptrend, dots trail below the price; once price falls below a dot, the dots 'flip' above the price – indicating a potential trend reversal (and vice versa for downtrends). Traders use SAR to set trailing stop-loss levels or identify when to switch from long to short positions.",
        "Aroon Indicator": "Consists of Aroon-Up and Aroon-Down lines that measure how many periods have passed since the last high or low (e.g., 25-day high/low). When Aroon-Up is high (near 100) and Aroon-Down is low, it means a recent new high was made (strong uptrend); conversely, a high Aroon-Down indicates a recent low (downtrend). The Aroon indicator helps identify emerging trends and range-bound conditions by gauging the recency of highs and lows."
    },
    "Momentum Indicators": {
        "Relative Strength Index (RSI)": "A popular momentum oscillator that measures the magnitude of recent price gains vs. losses over a lookback period (typically 14). RSI values oscillate between 0 and 100; readings above 70 suggest an asset may be overbought, while readings below 30 indicate oversold conditions. Traders use RSI to spot potential reversals or confirm trend strength (e.g., a bullish divergence when price makes a new low but RSI doesn’t).",
        "Moving Average Convergence Divergence (MACD)": "A trend-following momentum indicator that displays the relationship between two moving averages of price (commonly the 12-period and 26-period EMA). MACD is typically shown as the difference between those EMAs (the MACD line) along with a signal line (9-period EMA of MACD) and a histogram. Crossovers of the MACD line above/below the signal line can indicate shifts in momentum, while the histogram visualizes the rate of change of that momentum.",
        "Stochastic Oscillator": "A momentum oscillator that compares a security’s closing price to its price range over a recent period (typically 14 days). It is scaled 0 to 100 and consists of %K and %D lines. Readings above 80 generally indicate the asset is overbought, and readings below 20 indicate oversold conditions. Traders watch for %K crossing %D or for stochastic divergences from price as signals of potential reversals.",
        "Commodity Channel Index (CCI)": "A versatile oscillator that measures the current price level relative to an average price over a given period, essentially showing how far price deviates from its statistical mean. CCI is unbounded (can go above +100 or below –100); traditionally, values above +100 may indicate an asset is overbought or in a strong uptrend, while values below –100 indicate oversold conditions or a strong downtrend.",
        "Williams %R": "Williams Percent Range (Williams %R) is a momentum oscillator similar to Stochastic, which measures the level of the close relative to the highest high over a lookback period (commonly 14). It ranges from 0 to -100; values above -20 indicate overbought conditions, and below -80 indicate oversold."
    },
    "Volatility Indicators": {
        "Bollinger Bands": "A popular volatility channel consisting of a middle moving average with an upper and lower band plotted typically at ±2 standard deviations from the MA. The bands widen automatically when volatility increases and narrow when volatility decreases. Prices touching or exceeding the bands can indicate extreme conditions (potential pullback or reversal zones), while a squeeze (very narrow bands) often precedes a volatility breakout.",
        "Average True Range (ATR)": "A classic volatility indicator that computes the average of the True Range over a set period (often 14 days). True Range accounts for gaps by considering the current high-low range and comparing it to the previous close. A higher ATR value means the asset’s price swings are larger (more volatile), whereas a low ATR denotes smaller day-to-day ranges (quieter market).",
        "Keltner Channels": "A volatility-based envelope placed around an EMA with channel width determined by a multiple of ATR. Keltner Channels expand and contract with volatility similar to Bollinger Bands, but are based on ATR."
    },
    "Volume Indicators": {
        "On-Balance Volume (OBV)": "A cumulative volume indicator that adds the day’s volume when price closes up and subtracts volume when price closes down. OBV rises with positive volume flow (more volume on up days) and falls with negative volume flow.",
        "Accumulation/Distribution (A/D) Line": "A volume indicator that accumulates volume but weights it by where the price closes in the period’s range.",
        "Chaikin Money Flow (CMF)": "An oscillator derived from the A/D line that measures the amount of volume flowing into or out of an asset."
    },
    "Other Relevant Indicators": {
        "Fibonacci Retracement Levels": "Key horizontal levels (23.6%, 38.2%, 50%, 61.8%, 78.6%) used for support/resistance identification.",
        "Pivot Points": "Calculates support/resistance levels based on previous price action.",
        "Advance–Decline Line (A/D Line)": "A classic market breadth indicator measuring advancing vs. declining stocks.",
        "Arms Index (TRIN)": "Compares advancing vs. declining stocks and volume ratios to assess short-term sentiment."
    }
}