# Configuration file for Quantify-X
[api_keys]
# OpenAI Configuration
openai = "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"

# Google Gemini Configuration
gemini = "AIzaSyDZyCXwYbP5GYALOy90GqPIgQEGEpOh3bE"

[langchain]
# LangChain Configuration
tracing_v2 = true
endpoint = "https://api.smith.langchain.com"
api_key = "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"
