# Configuration file for Quantify-X
[api_keys]
# OpenAI Configuration
openai = "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"

# Google Gemini Configuration
gemini = "AIzaSyDZyCXwYbP5GYALOy90GqPIgQEGEpOh3bE"

[langchain]
# LangChain Configuration
tracing_v2 = true
endpoint = "https://api.smith.langchain.com"
api_key = "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"
